---
driver:
  name: vagrant
  vm_hostname: 'postfixadmin.local'
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]

provisioner:
  require_chef_omnibus: true

platforms:
# https://github.com/opscode-cookbooks/mysql/issues/228
# - name: ubuntu-10.04
#   run_list:
#     - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-6.0.10
  run_list:
  - recipe[apt]
- name: debian-7.8
  run_list:
  - recipe[apt]
- name: centos-5.11
- name: centos-6.6
- name: fedora-19
- name: fedora-20

suites:
- name: mysql
  run_list:
  - recipe[postfixadmin_test::mysql]
- name: postgresql
  excludes:
  # https://github.com/hw-cookbooks/postgresql/issues/97
  # https://github.com/hw-cookbooks/postgresql/issues/108
  - ubuntu-12.04
  - ubuntu-14.04
  - debian-6.0.10
  - debian-7.6
  - debian-7-0-x64
  run_list:
  - recipe[postfixadmin_test::postgresql]
- name: nginx
  excludes:
  # not supported by php-fpm cookbook
  - centos-5.11
  - fedora-19
  - fedora-20
  run_list:
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      web_server: nginx
- name: without-webserver
  run_list:
  - recipe[postfixadmin_test]
  attributes:
    postfixadmin:
      web_server: false
- name: map_files
  run_list:
  - recipe[postfix-full]
  - recipe[postfixadmin_test::map_files]
- name: lwrp
  run_list:
  - recipe[postfixadmin_test::lwrp]
- name: lwrp_ssl
  excludes:
  # apache2::mod_ssl not compatible
  - centos-5.11
  run_list:
  - recipe[postfixadmin_test::lwrp]
  attributes:
    postfixadmin:
      ssl: true
- name: lwrp_pgsql
  run_list:
  - recipe[postfixadmin_test::lwrp]
  excludes:
  # https://github.com/hw-cookbooks/postgresql/issues/97
  # https://github.com/hw-cookbooks/postgresql/issues/108
  - ubuntu-12.04
  - ubuntu-14.04
  - debian-6.0.10
  - debian-7.6
  - debian-7-0-x64
  attributes:
    postfixadmin:
      database:
        type: postgresql
    postgresql:
      password:
        postgres: vagrant_postgres
      ssl: true
- name: lwrp_port
  run_list:
  - recipe[postfixadmin_test::lwrp]
  attributes:
    postfixadmin:
      port: 8080
- name: lwrp_port_ssl
  # apache2::mod_ssl not compatible
  excludes:
  - centos-5.11
  run_list:
  - recipe[postfixadmin_test::lwrp]
  attributes:
    postfixadmin:
      port: 8443
      ssl: true
